# https://github.com/getredash/redash/blob/v7.0.0/docker-compose.yml
# https://github.com/getredash/redash/blob/v7.0.0/setup/docker-compose.yml
version: '3'
services:
  server:
    image: redash/redash:7.0.0.b18042
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 2
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_RATELIMIT_ENABLED: "false"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-fargate/redash
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
  create_db:
    image: redash/redash:7.0.0.b18042
    command: create_db
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-fargate/redash
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
  worker:
    image: redash/redash:7.0.0.b18042
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      QUEUES: "queries,scheduled_queries,celery,schemas"
      WORKERS_COUNT: 2
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-fargate/redash
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
