# https://github.com/getredash/redash/blob/v7.0.0/setup/docker-compose.yml
version: '3'
services:
  server:
    image: redash/redash:7.0.0.b18042
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 2
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://FIXME:6379/0"
      REDASH_COOKIE_SECRET: "FIXME"
      REDASH_SECRET_KEY: "FIXME"
      REDASH_THROTTLE_LOGIN_PATTERN: "150/hour"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-fargate/redash
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
  create_db:
    image: redash/redash:7.0.0.b18042
    command: create_db
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://FIXME:6379/0"
      REDASH_COOKIE_SECRET: "FIXME"
      REDASH_SECRET_KEY: "FIXME"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/dev-fargate/redash
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
  # scheduler:
  #   <<: *redash-service
  #   command: scheduler
  #   environment:
  #     QUEUES: "celery"
  #     WORKERS_COUNT: 1
  # scheduled_worker:
  #   <<: *redash-service
  #   command: worker
  #   environment:
  #     QUEUES: "scheduled_queries,schemas"
  #     WORKERS_COUNT: 1
  # adhoc_worker:
  #   <<: *redash-service
  #   command: worker
  #   environment:
  #     QUEUES: "queries"
  #     WORKERS_COUNT: 2
